#####Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).


#remote_theme: brockfanning/open-sdg@map-unit-and-series-support-with-subcategories
##brockfanning:map-unit-and-series-support-with-subcategories
#brockfanning/open-sdg@map-unit-and-series-support

#brockfanning/open-sdg@map-disaggregation-select-latest

#brockfanning:map-disaggregation-select-latest

#remote_theme: brockfanning/open-sdg@map-disaggregation-in-leaflet
#brockfanning:map-series-unit-behaviors
#remote_theme: brockfanning/open-sdg@selection-legend-text-to-the-left
#remote_theme: brockfanning/open-sdg@map-series-unit-behaviors

#remote_theme: open-sdg/open-sdg@2.1.0-dev

remote_theme: brockfanning/open-sdg@cookie-modal-high-contrast

#remote_theme: brockfanning/open-sdg@chart-tooltip-use-raw

#local-metadata-links
#remote_theme: open-sdg/open-sdg@alter-data-display-decimal-fix
#brockfanning:chart-tooltip-use-raw
# Replace this title as needed.
title: general.site_title
url: ""
environment: staging

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
